function [r_max_c, t_max_c] = compute_max_c(origin_c, sz_cart)

corners_c = [...
    1 1; ...
    sz_cart(1) 1; ...
    1 sz_cart(2); ...
    sz_cart ...
    ];
sums = sum((origin_c - corners_c) .^ 2, 2);
r_max_c = sqrt(max(sums));
t_max_c = 2 * pi * r_max_c;

end

